#!/usr/bin/env node
/**
 * One-shot cloud setup for CLA Learning
 * Usage: node scripts/setup-cloud.mjs
 *
 * Prerequisites:
 *   - Supabase account (free tier): https://supabase.com/dashboard
 *   - Optional: Vercel account for hosting
 */

import { execSync, spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env.local");
const migrationPath = join(root, "supabase/migrations/001_core_schema.sql");

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((r) => rl.question(q, r));

function run(cmd, opts = {}) {
  console.log(`\n→ ${cmd}`);
  return spawnSync(cmd, { shell: true, cwd: root, stdio: "inherit", ...opts });
}

function supabase(args) {
  return run(`npx supabase ${args}`);
}

async function main() {
  console.log(`
╔══════════════════════════════════════════════════════════╗
║  CLA Learning — Cloud setup (Supabase + optional Vercel) ║
╚══════════════════════════════════════════════════════════╝
`);

  const mode = (await ask("Setup mode — (1) I have Supabase keys already  (2) Use Supabase CLI  [1/2]: ")).trim() || "1";

  if (mode === "2") {
    console.log("\nStep 1: Log in to Supabase CLI (opens browser)…");
    supabase("login");
    const orgId = (await ask("\nOrg ID (from dashboard URL or `npx supabase orgs list`): ")).trim();
    const dbPassword = (await ask("Database password (min 8 chars, save this): ")).trim();
    console.log("\nCreating project cla-learning…");
    supabase(`projects create cla-learning --org-id ${orgId} --db-password "${dbPassword}" --region eu-central-1`);
    console.log("\nLinking project…");
    const ref = (await ask("Project ref (from dashboard URL, e.g. abcdefghijklmnop): ")).trim();
    supabase(`link --project-ref ${ref}`);
    console.log("\nPushing database schema…");
    supabase("db push");
    console.log("\nFetching API keys…");
    supabase("projects api-keys --project-ref " + ref);
    console.log("\nCopy the anon and service_role keys above into .env.local when prompted below.");
  } else {
    console.log(`
Manual Supabase setup (if you haven't yet):
  1. Go to https://supabase.com/dashboard → New project
  2. Name: cla-learning  |  Region: closest to Nairobi (eu-central-1 or eu-west-1)
  3. SQL Editor → paste contents of supabase/migrations/001_core_schema.sql → Run
  4. Project Settings → API → copy URL and anon key
`);
  }

  const url = (await ask("NEXT_PUBLIC_SUPABASE_URL: ")).trim();
  const anon = (await ask("NEXT_PUBLIC_SUPABASE_ANON_KEY: ")).trim();
  const service = (await ask("SUPABASE_SERVICE_ROLE_KEY (optional, for imports): ")).trim();

  const appUrl = (await ask("App URL [http://localhost:3000]: ")).trim() || "http://localhost:3000";

  const env = `# Generated by scripts/setup-cloud.mjs
NEXT_PUBLIC_SUPABASE_URL=${url}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}
${service ? `SUPABASE_SERVICE_ROLE_KEY=${service}\n` : ""}NEXT_PUBLIC_APP_URL=${appUrl}
`;
  writeFileSync(envPath, env);
  console.log(`\n✓ Wrote ${envPath}`);

  if (!existsSync(migrationPath)) {
    console.warn("⚠ Migration file not found — run SQL manually in Supabase dashboard.");
  } else if (mode === "1") {
    const ran = (await ask("\nHave you already run 001_core_schema.sql in Supabase? [y/N]: ")).trim().toLowerCase();
    if (ran !== "y") {
      console.log(`\nOpen SQL Editor and paste:\n  ${migrationPath}`);
    }
  }

  const deploy = (await ask("\nDeploy to Render? See scripts/setup-render.mjs for steps [y/N]: ")).trim().toLowerCase();
  if (deploy === "y") {
    console.log(`
Render setup:
  1. Push this folder to GitHub (or upload at github.com/new)
  2. https://dashboard.render.com → New → Blueprint → connect repo
  3. render.yaml configures the web service automatically
  4. Add env vars: NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, NEXT_PUBLIC_APP_URL
  Or run: npm run setup:render
`);
  }

  console.log(`
Done! Restart dev server:
  cd ~/Projects/cla-learning && npm run dev

Live URLs (local):
  http://localhost:3000/dashboard
  http://localhost:3000/login
`);
  rl.close();
}

main().catch((e) => {
  console.error(e);
  rl.close();
  process.exit(1);
});
