#!/usr/bin/env node
/**
 * Render deployment setup for CLA Learning
 * Usage: node scripts/setup-render.mjs
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env.local");
const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((r) => rl.question(q, r));

async function main() {
  console.log(`
╔══════════════════════════════════════════════════════╗
║  CLA Learning — Render + Supabase setup              ║
╚══════════════════════════════════════════════════════╝

Render deploys from Git (GitHub/GitLab/Bitbucket).
Without git locally, create a repo on github.com and upload this folder.
`);

  console.log(`Steps:
  1. Supabase: https://supabase.com/dashboard → New project "cla-learning"
  2. SQL Editor → run supabase/migrations/001_core_schema.sql
  3. GitHub: https://github.com/new → repo "cla-learning" → upload files
  4. Render: https://dashboard.render.com → New → Blueprint
     → connect repo → Render reads render.yaml automatically
  5. Set env vars in Render (or when Blueprint prompts):
     NEXT_PUBLIC_SUPABASE_URL
     NEXT_PUBLIC_SUPABASE_ANON_KEY
     NEXT_PUBLIC_APP_URL = https://cla-learning.onrender.com (your Render URL)
  6. Supabase → Authentication → URL Configuration:
     Site URL = your Render URL
     Redirect URLs = https://YOUR-APP.onrender.com/**
`);

  const url = (await ask("\nNEXT_PUBLIC_SUPABASE_URL (or Enter to skip): ")).trim();
  if (url) {
    const anon = (await ask("NEXT_PUBLIC_SUPABASE_ANON_KEY: ")).trim();
    const renderUrl = (await ask("Render URL [https://cla-learning.onrender.com]: ")).trim()
      || "https://cla-learning.onrender.com";

    const env = `# Generated by scripts/setup-render.mjs
NEXT_PUBLIC_SUPABASE_URL=${url}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}
NEXT_PUBLIC_APP_URL=${renderUrl}
`;
    writeFileSync(envPath, env);
    console.log(`\n✓ Wrote ${envPath}`);
    console.log("\nAdd the same 3 vars in Render → cla-learning → Environment.");
    console.log("\nSupabase Auth redirect URLs to add:");
    console.log(`  Site URL: ${renderUrl}`);
    console.log(`  Redirect: ${renderUrl}/**`);
  }

  rl.close();
}

main().catch((e) => {
  console.error(e);
  rl.close();
  process.exit(1);
});
